// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

function readFile(fileName) {
  var dirname = ((function () { 
    const path = require('path');
    
    return path.parse(__dirname).dir;
    })());
  var filePath = "src/input/" + fileName + ".txt";
  var fullPath = "" + dirname + "/" + filePath + "";
  return Fs.readFileSync(fullPath, "utf8").trim();
}

function splitLine(str, delim) {
  return str.split(delim);
}

exports.readFile = readFile;
exports.splitLine = splitLine;
/* fs Not a pure module */
