// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Input = require("../Input.bs.js");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_splice_call = require("rescript/lib/js/caml_splice_call.js");

function parseInput(param) {
  return Belt_Array.map(Input.readFile("day1").split("\n\n"), (function (x) {
                return Belt_Array.map(x.split("\n"), (function (x) {
                              return Belt_Option.getExn(Belt_Int.fromString(x));
                            }));
              }));
}

function getSumOfCalories(calories) {
  return Belt_Array.reduce(calories, 0, (function (acc, x) {
                return acc + x | 0;
              }));
}

function getTop3Calories(list) {
  return list.sort(function (a, b) {
                return b - a | 0;
              }).slice(0, 3);
}

function getMaxCalorie(list) {
  return Caml_splice_call.spliceApply(Math.max, [list]);
}

function part1(param) {
  console.log(Caml_splice_call.spliceApply(Math.max, [Belt_Array.map(parseInput(undefined), getSumOfCalories)]));
}

function part2(param) {
  console.log(getSumOfCalories(getTop3Calories(Belt_Array.map(parseInput(undefined), getSumOfCalories))));
}

part1(undefined);

part2(undefined);

exports.parseInput = parseInput;
exports.getSumOfCalories = getSumOfCalories;
exports.getTop3Calories = getTop3Calories;
exports.getMaxCalorie = getMaxCalorie;
exports.part1 = part1;
exports.part2 = part2;
/*  Not a pure module */
